// Mocks generated by Mockito 5.1.0 from annotations
// in detail/test/presentation/bloc/recommendation_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:core/domain/entities/movie.dart' as _i6;
import 'package:core/utils/failure.dart' as _i5;
import 'package:dartz/dartz.dart' as _i2;
import 'package:detail/domain/usecases/get_movie_recommendations.dart' as _i3;
import 'package:detail/domain/usecases/get_tv_series_recommendations.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GetMovieRecommendationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieRecommendationsUseCase extends _i1.Mock
    implements _i3.GetMovieRecommendationsUseCase {
  MockGetMovieRecommendationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Movie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
}

/// A class which mocks [GetTvSeriesRecommendationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeriesRecommendationsUseCase extends _i1.Mock
    implements _i7.GetTvSeriesRecommendationsUseCase {
  MockGetTvSeriesRecommendationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.Movie>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);
}
