// Mocks generated by Mockito 5.0.17 from annotations
// in ditonton/test/presentation/pages/search_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:ditonton/common/state_enum.dart' as _i5;
import 'package:ditonton/domain/entities/movie.dart' as _i6;
import 'package:ditonton/domain/usecases/search_movies.dart' as _i2;
import 'package:ditonton/domain/usecases/search_tv_series.dart' as _i3;
import 'package:ditonton/presentation/provider/movie_search_notifier.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeSearchMoviesUseCase_0 extends _i1.Fake
    implements _i2.SearchMoviesUseCase {}

class _FakeSearchTvSeriesUseCase_1 extends _i1.Fake
    implements _i3.SearchTvSeriesUseCase {}

/// A class which mocks [MovieSearchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchNotifier extends _i1.Mock
    implements _i4.MovieSearchNotifier {
  MockMovieSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchMoviesUseCase get searchMovies => (super.noSuchMethod(
      Invocation.getter(#searchMovies),
      returnValue: _FakeSearchMoviesUseCase_0()) as _i2.SearchMoviesUseCase);
  @override
  _i3.SearchTvSeriesUseCase get searchTvSeries =>
      (super.noSuchMethod(Invocation.getter(#searchTvSeries),
              returnValue: _FakeSearchTvSeriesUseCase_1())
          as _i3.SearchTvSeriesUseCase);
  @override
  _i5.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i5.RequestState.Empty) as _i5.RequestState);
  @override
  List<_i6.Movie> get searchResult =>
      (super.noSuchMethod(Invocation.getter(#searchResult),
          returnValue: <_i6.Movie>[]) as List<_i6.Movie>);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void resetData() => super.noSuchMethod(Invocation.method(#resetData, []),
      returnValueForMissingStub: null);
  @override
  _i7.Future<void> fetchMovieSearch(
          String? query, _i5.CategoryMovie? category) =>
      (super.noSuchMethod(
          Invocation.method(#fetchMovieSearch, [query, category]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  void addListener(_i8.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i8.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
